backend:
  name: github
  repo: sharikharis/harissharik
  branch: main
  base_url: https://api.netlify.app
  auth_endpoint: /auth
  client_id: Ov23liXv9vsmrXLHV0d2

media_folder: "images"
public_folder: "images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "admin/data" # যেখানে আপনার posts.json আছে
    format: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["বই রিভিউ", "প্রবন্ধ", "গল্প"]}
      - {label: "Date", name: "date", widget: "string", hint: "উদাহরণ: মে ০৮, ২০২৬"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Full Content", name: "body", widget: "markdown"}
